name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull akalankaparallax123/dockercicd:latest
    - name: Delete Old docker container
      run: sudo docker rm -f curfox_ml || true
    - name: Run Docker Container
      run: sudo docker run -d -p 7860:7860 --name curfox_ml akalankaparallax123/dockercicd