name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
    - name: Pull Docker image
      run: docker pull akalankaparallax123/dockercicd:latest

    - name: Delete Old Docker Container
      run: docker rm -f curfox_ml || true

    - name: Run Docker Container
      run: docker run -d -p 7860:7860 --name curfox_ml akalankaparallax123/dockercicd:latest
